### ISSUE TITLE
Creación plantilla Plan Anual de Auditoría

### ISSUE THREAD

**Issue by edwargl7** [udistrital/sisifo_documentacion#185]
Se requiere realizar ajustes en la plantilla para permitir agregar que según el mes elegido se rellene la casilla. Así como la definición de las variables para cada campo de la plantilla.
![image](https://github.com/user-attachments/assets/20d778ab-3005-448c-bc75-9117d1b11f8e)

**Sub Tareas**

- [x] Ajustes plantilla HTML, describiendo las variables requeridas.

**Criterios de aceptación**

- [x] Creación y cargue en la carpeta de plantillas de Sísifo.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by jucastro94** [comment]
se ajustan variables para el llenado de la tabla
![Image](https://github.com/user-attachments/assets/5023290c-a496-46f9-a48c-72ed298a1ca7)

**Comment by edwargl7** [comment]
Se realiza la revisión con @cjgonzalezp y se debe revisar la posibilidad de dar más espacio a la columna de título de actividades similar al diseño propuesto.

**Comment by jucastro94** [comment]
se terminan de establecer variables para codigo, objetivo del programa, alcance, criterios y recursos
```html
<!DOCTYPE html><html lang=\"es\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Plan Anual de Auditoría (PAA)</title>
</head><body><div class=\"container\">
<table class=\"header-table\">
	<tr>
		<td rowspan=\"3\" class=\"logo\"><img src=\"{{ logoUDistrital }}\" alt=\"Logo\"></td>
		<td colspan=\"1\"><strong>PLAN ANUAL DE AUDITORÍA (PAA)</strong></td>
		<td colspan=\"1\"><strong>Código:</strong> {{ codigo }}</td>
		<td rowspan=\"3\" class=\"logo\"><img src=\"{{ logoSIGUD }}\" alt=\"SIGUD\"></td>
	</tr>
	<tr>
		<td><strong>Macroproceso:</strong> Evaluación y Control</td>
		<td><strong>Versión:</strong> 02</td>
	</tr>
	<tr>
		<td><strong>Proceso:</strong> {{ proceso }}</td>
		<td><strong>Fecha de Aprobación:</strong> 20/11/2015</td>
	</tr>
</table>
<table class=\"content-table\">
	<tr><td><strong>Objetivo del Programa: </strong>{{ objetivo }}</td></tr>
	<tr><td><strong>Alcance del Programa: </strong>{{ alcance }}</td></tr>
	<tr><td><strong>Criterios:</strong>{{ criterios }}</td></tr>
	<tr><td><strong>Recursos:</strong>{{ recursos }}</td></tr>
</table>
<table class=\"schedule-table\">
	<tr>
		<th class=\"cabecera-table\" rowspan=\"2\">TÍTULO DE LA ACTIVIDAD</th>
		<th class=\"cabecera-table\" colspan=\"6\">CRONOGRAMA DE ACTIVIDADES - I SEM.</th>
		<th class=\"cabecera-table\" colspan=\"6\">CRONOGRAMA DE ACTIVIDADES - II SEM.</th>
	</tr>
	<tr>
		<th>enero</th>
		<th>febrero</th>
		<th>marzo</th>
		<th>abril</th>
		<th>mayo</th>
		<th>junio</th>
		<th>julio</th>
		<th>agosto</th>
		<th>septiembre</th>
		<th>octubre</th>
		<th>noviembre</th>
		<th>diciembre</th>
	</tr>
	{% for item in items %}
	<tr>
		<td class=\"actividad\">{{ item.actividad }}</td>
		<td class=\"elemento {{ item.enero }}\"></td>
		<td class=\"elemento {{ item.febrero }}\"></td>
		<td class=\"elemento {{ item.marzo }}\"></td>
		<td class=\"elemento {{ item.abril }}\"></td>
		<td class=\"elemento {{ item.mayo }}\"></td>
		<td class=\"elemento {{ item.junio }}\"></td>
		<td class=\"elemento {{ item.julio }}\"></td>
		<td class=\"elemento {{ item.agosto }}\"></td>
		<td class=\"elemento {{ item.septiembre }}\"></td>
		<td class=\"elemento {{ item.octubre }}\"></td>
		<td class=\"elemento {{ item.noviembre }}\"></td>
		<td class=\"elemento {{ item.diciembre }}\"></td>
	</tr>{% endfor %}
</table>
</div>
</body>
</html>

```

**Comment by jucastro94** [comment]
se ajusta css para dar mas espacio a la columna actividades, ubicar las imagenes de los logos y marcar casillas con color en lugar de "x"

```css
@page {size: 8.5in 14in;
 margin: 0;
padding: 0;
}
@page :first {margin-top: 1in;
margin-right: 0.5in;
margin-bottom: 1in;
margin-left: 0.51in;
 }
@page :right {margin-top: 1in;
margin-right: 0.5in;
margin-bottom: 1in;
margin-left: 0.5in;
 }
@page :left {margin-top: 1in;
margin-right: 0.5in;
margin-bottom: 1in;
margin-left: 0.5in;
 }
body {font-family: Arial, sans-serif;
background-color: #f4f4f4;
margin: 0;
padding: 0;
width: 100%;
height: 100%;
}
.container {width: 100%;
margin: 0px auto;
padding: 0px;
padding-top: 0px;
padding-bottom: 0px;
padding-left: 0px;
padding-right: 0px;
background-color: white;
box-shadow: 0 0 10px rgba(0,0,0,0.1);
box-sizing: border-box;
height: 100%;
 }
table{table-layout: fixed;
margin: 0;
padding: 0;
width: 100%}
.header-table, .content-table, .schedule-table {width: 100%;
border-collapse: collapse;
}
.content-table tr td {font-size: 12px;
}
.header-table th, .header-table td, .content-table th, .content-table td, .schedule-table th, .schedule-table td {border: 1px solid black;
padding: 2px;
text-align: left;
}
.header-table {margin-bottom: 20px;
}
.header-table th {background-color: #e6e6e6;
font-size: 8px;
}
.header-table td {width: auto;
}

.logo {
text-align: center;
vertical-align: middle;
}
.logo img { max-width: 100%;
}

.section-title {font-weight: bold;
 background-color: #e6e6e6;
padding: 5px;
}
.schedule-table{
	table-layout: auto;
}
.schedule-table th {background-color: #b3c6ff;
text-align: center;
font-size: 7px;
word-break: break-all;
hyphens: auto;
}
 .schedule-table td {text-align: left;
font-size: 10px;
word-break: break-all;
hyphens: auto;
}
.cabecera-table{font-size: 10;
}
.marcado{
	background-color:gray;
}
.actividad{
	width:45%;
	max-width:45%;
}
.elemento{
	width:auto;
}
}
```
